plugins {
    id 'java'
    id 'application'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

description = 'event-processor-spring-cloud-function'

application {
    mainClass = 'org.kergru.iotplatform.processor.function.SpringCloudFunctionProcessorApplication'
}

dependencies {
    implementation project(':common-events')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.cloud:spring-cloud-stream'
    implementation 'org.springframework.cloud:spring-cloud-stream-binder-kafka'
    implementation 'io.confluent:kafka-avro-serializer:8.1.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.junit.jupiter:junit-jupiter:6.0.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
