FROM eclipse-temurin:21-jre
WORKDIR /app
COPY event-processor-spring-cloud-function/build/install/event-processor-spring-cloud-function/ ./
ENTRYPOINT ["/app/bin/event-processor-spring-cloud-function"]
